image: alpine:3.10


variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - apk update
  - apk --no-cache add openjdk11 --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
  - apk add xvfb-run

build:
  stage: build
  script: xvfb-run gradle build --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

pages:
  stage: deploy
  script:
    - gradle javadoc
    - cp -r build/docs/javadoc/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 day
  only:
    - main